version: "3.9"

services:

    ai4-papi-prod:
        image: "registry.services.ai4os.eu/ai4os/ai4-papi:prod"
        restart: always
        environment:
            - NOMAD_ADDR=https://193.146.75.205:4646
            - ACCOUNTING_PTH=/home/ai4-accounting
            - ZENODO_TOKEN=*****************************
            - PAPI_GITHUB_TOKEN=************************
            - MAILING_TOKEN=****************************
            - HARBOR_ROBOT_PASSWORD=********************
            - PAPI_JENKINS_TOKEN=***********************
            - PAPI_PROVENANCE_TOKEN=********************
        volumes:
            - /home/ubuntu/nomad-certs/nomad-federated:/home/nomad-certs
            - /home/ubuntu/ai4-accounting:/home/ai4-accounting
        ports:
            - 8080:80


    ai4-papi-dev:
        image: "registry.services.ai4os.eu/ai4os/ai4-papi:dev"
        restart: always
        environment:
            - NOMAD_ADDR=https://193.146.75.205:4646
            - ACCOUNTING_PTH=/home/ai4-accounting
            - ZENODO_TOKEN=*****************************
            - PAPI_GITHUB_TOKEN=************************
            - MAILING_TOKEN=****************************
            - HARBOR_ROBOT_PASSWORD=********************
            - PAPI_JENKINS_TOKEN=***********************
            - PAPI_PROVENANCE_TOKEN=********************
        volumes:
            - /home/ubuntu/nomad-certs/nomad-federated:/home/nomad-certs
            - /home/ubuntu/ai4-accounting:/home/ai4-accounting
        ports:
            - 8081:80
