# Based on: https://docs.docker.com/build/ci/github-actions/test-before-push/

name: Build ai4-papi:prod docker image

on:
  push:
    tags:
      - v1.**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.HARBOR_URL  }}
          username: ${{ vars.HARBOR_USERNAME  }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: test-image
          file: docker/Dockerfile

      - name: Test - Basic init (dev mode)
        run: |
              docker run \
                -e IS_PROD=False \
                --rm \
                test-image \
                /bin/bash -c "source /root/.local/share/pipx/venvs/ai4papi/bin/activate && python3 -c 'import ai4papi'"

      - name: Get short commit SHA
        id: vars
        run: echo "GIT_COMMIT_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.HARBOR_URL }}/ai4os/ai4-papi:latest
            ${{ vars.HARBOR_URL }}/ai4os/ai4-papi:prod
            ${{ vars.HARBOR_URL }}/ai4os/ai4-papi:prod-${{ env.GIT_COMMIT_SHORT }}
            ${{ secrets.DOCKERHUB_USERNAME }}/ai4-papi:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ai4-papi:prod
          file: docker/Dockerfile
